version: '3.8'

services:
  # Backend - ADK API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: venturebots
    container_name: venturebots-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - Streamlit
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: venturebots
    container_name: venturebots-app
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - ADK_BACKEND_URL=http://backend:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 